### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mehdiben7** [TJusab/solid-vault#2]
Updating the README.md file with actual content about the repository. Here is ideas that we could include to populate the file:
* Content from the Devpost project
* Usage & contribution

**Comment by Rishav1707** [comment]
Can you provide me with a brief introduction to this repo?
Some screenshots?
Usage of this repo?
Features of this project?

**Comment by mehdiben7** [comment]
Absolutely! 
These are actually things we need to include in the README.md file. In the meantime, you can checkout the project's [Devpost](https://devpost.com/software/solid-vault).
